# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import agenda_pb2 as agenda__pb2


class ManagerStub(object):

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.addPerson = channel.unary_unary(
        '/Manager/addPerson',
        request_serializer=agenda__pb2.Person.SerializeToString,
        response_deserializer=agenda__pb2.BooleanReply.FromString,
        )
    self.delPerson = channel.unary_unary(
        '/Manager/delPerson',
        request_serializer=agenda__pb2.PersonId.SerializeToString,
        response_deserializer=agenda__pb2.BooleanReply.FromString,
        )
    self.searchPersonName = channel.unary_stream(
        '/Manager/searchPersonName',
        request_serializer=agenda__pb2.PersonName.SerializeToString,
        response_deserializer=agenda__pb2.AddressBook.FromString,
        )
    self.searchPersonId = channel.unary_unary(
        '/Manager/searchPersonId',
        request_serializer=agenda__pb2.PersonId.SerializeToString,
        response_deserializer=agenda__pb2.PersonReply.FromString,
        )
    self.listContacts = channel.unary_stream(
        '/Manager/listContacts',
        request_serializer=agenda__pb2.ContactsRequest.SerializeToString,
        response_deserializer=agenda__pb2.AddressBook.FromString,
        )


class ManagerServicer(object):

  def addPerson(self, request, context):
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def delPerson(self, request, context):
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def searchPersonName(self, request, context):
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def searchPersonId(self, request, context):
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def listContacts(self, request, context):
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_ManagerServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'addPerson': grpc.unary_unary_rpc_method_handler(
          servicer.addPerson,
          request_deserializer=agenda__pb2.Person.FromString,
          response_serializer=agenda__pb2.BooleanReply.SerializeToString,
      ),
      'delPerson': grpc.unary_unary_rpc_method_handler(
          servicer.delPerson,
          request_deserializer=agenda__pb2.PersonId.FromString,
          response_serializer=agenda__pb2.BooleanReply.SerializeToString,
      ),
      'searchPersonName': grpc.unary_stream_rpc_method_handler(
          servicer.searchPersonName,
          request_deserializer=agenda__pb2.PersonName.FromString,
          response_serializer=agenda__pb2.AddressBook.SerializeToString,
      ),
      'searchPersonId': grpc.unary_unary_rpc_method_handler(
          servicer.searchPersonId,
          request_deserializer=agenda__pb2.PersonId.FromString,
          response_serializer=agenda__pb2.PersonReply.SerializeToString,
      ),
      'listContacts': grpc.unary_stream_rpc_method_handler(
          servicer.listContacts,
          request_deserializer=agenda__pb2.ContactsRequest.FromString,
          response_serializer=agenda__pb2.AddressBook.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'Manager', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
